// packages/vue-list/src/components/empty.vue
<template>
  <div v-if="showEmpty" class="vue-list__empty">
    <slot>
      <p>No data found!</p>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListEmpty',
})

const { listState } = useListContext()

const showEmpty = computed(() => {
  const state = listState.value
  return (
    !state.loader.initialLoading &&
    !state.loader.isLoading &&
    state.isEmpty &&
    !state.error
  )
})
</script>

// packages/react-list/src/components/empty.tsx
import { memo, type ReactNode } from "react";
import { useListContext } from "../context/list-context";

type ListEmptyProps = {
  children?: ReactNode;
};

export const ListEmpty = memo(({ children }: ListEmptyProps) => {
  const { listState } = useListContext();
  const { data: items, loader, error } = listState;
  const { isLoading, initialLoading } = loader;

  if (items?.length > 0 || initialLoading || isLoading || error) {
    return null;
  }

  return (
    <div className="react-list-empty">
      {children || (
        <div>
          <p>No data found!</p>
        </div>
      )}
    </div>
  );
});
