// packages/vue-list/src/components/loader.vue
<template>
  <div
    v-if="listState.loader.isLoading && !listState.loader.initialLoading"
    class="vue-list__loader"
    :class="positionClass"
  >
    <slot v-bind="scope">
      <p>Loading...</p>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { LoaderComponentOptions, LoaderScope } from '@7span/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListLoader',
})

const props = withDefaults(defineProps<LoaderComponentOptions>(), {
  position: 'overlay',
})

const { listState } = useListContext()

const positionClass = computed(() => `vue-list__loader--${props.position}`)

const scope = computed((): LoaderScope => ({
  isLoading: listState.value.loader.isLoading,
}))
</script>

// packages/react-list/src/components/loader.tsx
import { memo, useMemo, type ReactNode } from "react";
import type {
  LoaderComponentOptions,
  LoaderScope,
} from "@7span/list-types";
import { useListContext } from "../context/list-context";

type ReactListLoaderProps = LoaderComponentOptions & {
  children?: ReactNode | ((scope: LoaderScope) => ReactNode);
};

export const ReactListLoader = memo(
  ({ children, position = "overlay" }: ReactListLoaderProps) => {
    const { listState } = useListContext();
    const { loader } = listState;
    const { isLoading, initialLoading } = loader;

    const scope = useMemo(
      (): LoaderScope => ({
        isLoading,
      }),
      [isLoading]
    );

    if (!initialLoading && !isLoading) {
      return null;
    }

    return (
      <div className={`react-list-loader react-list-loader--${position}`}>
        {typeof children === "function"
          ? children(scope)
          : children || (
              <div>
                <p>Loading...</p>
              </div>
            )}
      </div>
    );
  }
);
