// packages/vue-list/src/components/load-more.vue
<template>
  <div v-if="showContent" class="vue-list__load-more">
    <slot v-bind="scope">
      <button v-if="scope.hasMoreItems" type="button" @click="scope.loadMore">Load More</button>
      <p v-else>— That's all —</p>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { LoadMoreScope } from '@7span/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'VueListLoadMore',
})

const { listState } = useListContext()

const showContent = computed(() => {
  const state = listState.value
  return state.data.length > 0 && !state.error
})

const scope = computed((): LoadMoreScope => {
  const state = listState.value
  const { page, perPage } = state.pagination

  return {
    isLoading: state.loader.isLoading,
    loadMore: state.loadMore,
    hasMoreItems: page * perPage < state.count,
  }
})
</script>

// packages/react-list/src/components/load-more.tsx
import { memo, useCallback, useMemo, type ReactNode } from "react";
import type { LoadMoreScope } from "@7span/list-types";
import { useListContext } from "../context/list-context";

type ReactListLoadMoreProps = {
  children?: (scope: LoadMoreScope) => ReactNode;
};

export const ReactListLoadMore = memo(({ children }: ReactListLoadMoreProps) => {
  const { listState } = useListContext();
  const { data, count, pagination, setPage, loader, error } = listState;
  const { page, perPage } = pagination;
  const { isLoading } = loader;

  const hasMoreItems = useMemo(
    () => page * perPage < count,
    [page, perPage, count]
  );

  const loadMore = useCallback(() => {
    if (hasMoreItems && !isLoading) {
      setPage(page + 1);
    }
  }, [hasMoreItems, isLoading, setPage, page]);

  const scope = useMemo(
    (): LoadMoreScope => ({
      isLoading,
      loadMore,
      hasMoreItems,
    }),
    [isLoading, loadMore, hasMoreItems]
  );

  if (!data || data.length === 0) {
    return null;
  }

  if (error) {
    return null;
  }

  return children?.(scope) ?? null;
});
