// packages/vue-list/src/components/refresh.vue
<template>
  <div v-if="!listState.loader.initialLoading" class="vue-list__refresh">
    <slot v-bind="scope">
      <button type="button" :disabled="scope.isLoading" @click="scope.refresh">
        {{ scope.isLoading ? 'Loading...' : 'Refresh' }}
      </button>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { RefreshScope } from '@7span/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListRefresh',
})

const { listState } = useListContext()

const scope = computed((): RefreshScope => ({
  isLoading: listState.value.loader.isLoading,
  refresh: () => listState.value.refresh({ isRefresh: true }),
}))
</script>

// packages/react-list/src/components/refresh.tsx
import { memo, useCallback, useMemo, type ReactNode } from "react";
import type { RefreshScope } from "@7span/list-types";
import { useListContext } from "../context/list-context";

type ListRefreshProps = {
  children?: (scope: RefreshScope) => ReactNode;
};

export const ListRefresh = memo(({ children }: ListRefreshProps) => {
  const { listState } = useListContext();
  const { loader, refresh } = listState;
  const { isLoading, initialLoading } = loader;

  const handleRefresh = useCallback(() => {
    refresh({ isRefresh: true });
  }, [refresh]);

  const scope = useMemo(
    (): RefreshScope => ({
      isLoading,
      refresh: handleRefresh,
    }),
    [isLoading, handleRefresh]
  );

  if (initialLoading) return null;

  if (children) {
    return children(scope);
  }

  return (
    <div className="react-list-refresh">
      <button onClick={handleRefresh} disabled={isLoading}>
        {isLoading ? "Loading..." : "Refresh"}
      </button>
    </div>
  );
});
