// packages/vue/src/components/go-to.vue
<template>
  <div v-if="showContent" class="vue-list__go-to">
    <slot v-bind="scope">
      <select
        :value="scope.page"
        @input="scope.setPage(Number(($event.target as HTMLSelectElement).value))"
      >
        <option v-for="pageNum in scope.pages" :key="`page-${pageNum}`" :value="pageNum">
          Page {{ pageNum }}
        </option>
      </select>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { GoToScope } from '@shilp.dev/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListGoTo',
})

const { listState } = useListContext()

const showContent = computed(() => {
  const state = listState.value
  return !state.loader.initialLoading && state.data.length > 0 && !state.error
})

const scope = computed((): GoToScope => {
  const state = listState.value
  const { page, perPage } = state.pagination
  const pagesCount = Math.ceil(state.count / perPage)
  const pages = Array.from({ length: pagesCount }, (_, index) => index + 1)

  return {
    page,
    pages,
    pagesCount,
    setPage: state.setPage,
  }
})
</script>

// packages/react/src/components/go-to.tsx
import { memo, useCallback, useMemo, type ReactNode } from 'react'
import type { GoToScope } from '@shilp.dev/list-types'
import { useListContext } from '../context/list-context'

type ListGoToProps = {
  children?: (scope: GoToScope) => ReactNode
}

export const ListGoTo = memo(({ children }: ListGoToProps) => {
  const { listState } = useListContext()
  const { data, count, pagination, setPage, loader, error } = listState
  const { page, perPage } = pagination
  const { initialLoading } = loader

  const { pages, pagesCount } = useMemo(() => {
    const pagesCount = Math.ceil(count / perPage)
    const pages = Array.from({ length: pagesCount }, (_, i) => i + 1)
    return { pages, pagesCount }
  }, [count, perPage])

  const handlePageChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      setPage(Number(e.target.value))
    },
    [setPage],
  )

  const scope = useMemo(
    (): GoToScope => ({
      setPage,
      page,
      pages,
      pagesCount,
    }),
    [setPage, page, pages, pagesCount],
  )

  if (initialLoading) return null

  if (!data || data.length === 0) {
    return null
  }

  if (error) {
    return null
  }

  return (
    <div className="react-list-go-to">
      {children ? (
        children(scope)
      ) : (
        <select value={page} onChange={handlePageChange}>
          {pages.map((pageNum) => (
            <option key={`page-${pageNum}`} value={pageNum}>
              Page {pageNum}
            </option>
          ))}
        </select>
      )}
    </div>
  )
})
