// packages/vue/src/components/loader.vue
<template>
  <div
    v-if="listState.loader.isLoading && !listState.loader.initialLoading"
    class="vue-list__loader"
  >
    <slot v-bind="scope">
      <p>Loading...</p>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { LoaderScope } from '../../../../shared'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListLoader',
})

const { listState } = useListContext()

const scope = computed(
  (): LoaderScope => ({
    isLoading: listState.value.loader.isLoading,
  }),
)
</script>

// packages/react/src/components/loader.tsx
import { type ReactNode } from 'react'
import type { LoaderScope } from '../../../../shared'
import { useListContext } from '../context/list-context'

type ListLoaderProps = {
  children?: ReactNode | ((scope: LoaderScope) => ReactNode)
}

export const ListLoader = ({ children }: ListLoaderProps) => {
  const { listState } = useListContext()
  const { loader } = listState
  const { isLoading, initialLoading } = loader

  const scope: LoaderScope = {
    isLoading,
  }

  if (initialLoading || !isLoading) {
    return null
  }

  return (
    <div className="react-list__loader">
      {typeof children === 'function'
        ? children(scope)
        : children || (
            <div>
              <p>Loading...</p>
            </div>
          )}
    </div>
  )
}
