// packages/vue-list/src/components/load-more.vue
<template>
  <div v-if="showContent" class="vue-list__load-more">
    <slot v-bind="scope">
      <button v-if="scope.hasMoreItems" type="button" @click="scope.loadMore">Load More</button>
      <p v-else>— That's all —</p>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { LoadMoreScope } from '@7span/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'VueListLoadMore',
})

const { listState } = useListContext()

const showContent = computed(() => {
  const state = listState.value
  return state.data.length > 0 && !state.error
})

const scope = computed((): LoadMoreScope => {
  const state = listState.value
  const { page, perPage } = state.pagination

  return {
    isLoading: state.loader.isLoading,
    loadMore: state.loadMore,
    hasMoreItems: page * perPage < state.count,
  }
})
</script>

// packages/react/src/components/load-more.tsx
import { type ReactNode } from 'react'
import type { LoadMoreScope } from '../../../../shared'
import { useListContext } from '../context/list-context'

type ListLoadMoreProps = {
  children?: (scope: LoadMoreScope) => ReactNode
}

export const ListLoadMore = ({ children }: ListLoadMoreProps) => {
  const { listState } = useListContext()
  const { data, count, pagination, loader, error, loadMore } = listState
  const { page, perPage } = pagination
  const { isLoading } = loader

  const hasMoreItems = page * perPage < count

  const scope: LoadMoreScope = {
    isLoading,
    loadMore,
    hasMoreItems,
  }

  if (!data || data.length === 0) {
    return null
  }

  if (error) {
    return null
  }

  return (
    <div className="react-list__load-more">
      {typeof children === 'function' ? (
        children(scope)
      ) : children ? (
        children
      ) : hasMoreItems ? (
        <button type="button" onClick={loadMore}>
          Load More
        </button>
      ) : (
        <p>— That&apos;s all —</p>
      )}
    </div>
  )
}
