// packages/vue/src/components/pagination.vue
<template>
  <div v-if="showContent" class="vue-list__pagination">
    <slot v-bind="scope">
      <slot name="first" v-bind="scope">
        <button type="button" :disabled="!scope.hasPrev" @click="scope.first">First</button>
      </slot>

      <slot name="prev" v-bind="scope">
        <button type="button" :disabled="!scope.hasPrev" @click="scope.prev">Prev</button>
      </slot>

      <slot name="pages" v-bind="scope">
        <template v-for="item in scope.pagesToDisplay" :key="item">
          <slot name="page" :page="item" :isActive="item === scope.page">
            <span v-if="item === scope.page">{{ item }}</span>
            <button v-else type="button" @click="scope.setPage(item)">
              {{ item }}
            </button>
          </slot>
        </template>
      </slot>

      <slot name="next" v-bind="scope">
        <button type="button" :disabled="!scope.hasNext" @click="scope.next">Next</button>
      </slot>

      <slot name="last" v-bind="scope">
        <button type="button" :disabled="!scope.hasNext" @click="scope.last">Last</button>
      </slot>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { PaginationComponentOptions, PaginationScope } from '@shilp.dev/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListPagination',
})

const props = withDefaults(defineProps<PaginationComponentOptions>(), {
  pageLinks: 5,
})

const { listState } = useListContext()

const showContent = computed(() => {
  const state = listState.value
  return !state.loader.initialLoading && state.data.length > 0 && !state.error
})

const scope = computed((): PaginationScope => {
  const state = listState.value
  const { page, perPage } = state.pagination
  const total = state.count
  const pagesCount = Math.ceil(total / perPage)
  const halfWay = Math.floor(props.pageLinks / 2)
  const hasNext = page * perPage < total
  const hasPrev = page !== 1
  const pageCount = Math.min(props.pageLinks, pagesCount)
  const pages = Array.from({ length: pageCount })

  let pagesToDisplay: number[]
  if (page <= halfWay) {
    pagesToDisplay = pages.map((_, index) => index + 1)
  } else if (pagesCount - page < halfWay) {
    pagesToDisplay = pages.map((_, index) => pagesCount - index).reverse()
  } else {
    pagesToDisplay = pages.map((_, index) => page - halfWay + index)
  }

  return {
    page,
    perPage,
    count: total,
    pagesCount,
    halfWay,
    hasNext,
    hasPrev,
    pagesToDisplay,
    prev: () => state.setPage(page - 1),
    next: () => state.setPage(page + 1),
    first: () => state.setPage(1),
    last: () => state.setPage(pagesCount),
    setPage: (nextPage: number) => state.setPage(nextPage),
  }
})
</script>

// packages/react/src/components/pagination.tsx
import { memo, useMemo, type ReactNode } from 'react'
import type {
  PaginationComponentOptions,
  PaginationScope,
  RenderPageArgs,
} from '@shilp.dev/list-types'
import { useListContext } from '../context/list-context'

type ListPaginationProps = PaginationComponentOptions & {
  children?: (scope: PaginationScope) => ReactNode
  renderFirst?: (scope: PaginationScope) => ReactNode
  renderPrev?: (scope: PaginationScope) => ReactNode
  renderPages?: (scope: PaginationScope) => ReactNode
  renderPage?: (scope: RenderPageArgs) => ReactNode
  renderNext?: (scope: PaginationScope) => ReactNode
  renderLast?: (scope: PaginationScope) => ReactNode
}

export const ListPagination = memo(
  ({
    children,
    pageLinks = 5,
    renderFirst,
    renderPrev,
    renderPages,
    renderPage,
    renderNext,
    renderLast,
  }: ListPaginationProps) => {
    const { listState } = useListContext()
    const { data, count, pagination, setPage, loader, error } = listState
    const { page, perPage } = pagination
    const { initialLoading } = loader

    const paginationState = useMemo(() => {
      const pagesCount = Math.ceil(count / perPage)
      const halfWay = Math.floor(pageLinks / 2)
      const hasNext = page * perPage < count
      const hasPrev = page !== 1
      return { pagesCount, halfWay, hasNext, hasPrev }
    }, [count, perPage, page, pageLinks])

    const pagesToDisplay = useMemo(() => {
      const { pagesCount, halfWay } = paginationState
      const pages = Array.from({ length: Math.min(pageLinks, pagesCount) })

      if (page <= halfWay) {
        return pages.map((_, index) => index + 1)
      } else if (pagesCount - page < halfWay) {
        return pages.map((_, index) => pagesCount - index).reverse()
      } else {
        return pages.map((_, index) => page - halfWay + index)
      }
    }, [page, pageLinks, paginationState])

    const navigation = useMemo(
      () => ({
        prev: () => setPage(page - 1),
        next: () => setPage(page + 1),
        first: () => setPage(1),
        last: () => setPage(paginationState.pagesCount),
        setPage: (newPage: number) => setPage(newPage),
      }),
      [setPage, page, paginationState.pagesCount],
    )

    const scope = useMemo(
      (): PaginationScope => ({
        page,
        perPage,
        count,
        ...paginationState,
        pagesToDisplay,
        ...navigation,
      }),
      [page, perPage, count, paginationState, pagesToDisplay, navigation],
    )

    if (initialLoading) return null

    if (!data || data.length === 0) {
      return null
    }

    if (error) {
      return null
    }

    if (children) {
      return children(scope)
    }

    return (
      <div className="react-list-pagination">
        {renderFirst ? (
          renderFirst(scope)
        ) : (
          <button type="button" disabled={!paginationState.hasPrev} onClick={navigation.first}>
            First
          </button>
        )}

        {renderPrev ? (
          renderPrev(scope)
        ) : (
          <button type="button" disabled={!paginationState.hasPrev} onClick={navigation.prev}>
            Prev
          </button>
        )}

        {renderPages ? (
          renderPages(scope)
        ) : (
          <div>
            {pagesToDisplay.map((pageNum) => {
              const isActive = pageNum === page
              const pageScope: RenderPageArgs = { ...scope, page: pageNum, isActive }

              return renderPage ? (
                renderPage(pageScope)
              ) : (
                <div key={`page-${pageNum}`}>
                  {isActive ? (
                    <span>{pageNum}</span>
                  ) : (
                    <button type="button" onClick={() => navigation.setPage(pageNum)}>
                      {pageNum}
                    </button>
                  )}
                </div>
              )
            })}
          </div>
        )}

        {renderNext ? (
          renderNext(scope)
        ) : (
          <button type="button" disabled={!paginationState.hasNext} onClick={navigation.next}>
            Next
          </button>
        )}

        {renderLast ? (
          renderLast(scope)
        ) : (
          <button type="button" disabled={!paginationState.hasNext} onClick={navigation.last}>
            Last
          </button>
        )}
      </div>
    )
  },
)
