// packages/vue/src/components/rows.vue
<template>
  <div
    v-if="!listState.loader.initialLoading && !listState.error && !listState.isEmpty"
    class="vue-list__rows"
  >
    <slot v-bind="scope">
      <div v-for="(row, index) in scope.rows" :key="getRowId(row, listState.idKey) ?? index">
        <slot name="row" :row="row" :index="index">
          <pre>{{ row }}</pre>
        </slot>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { RowsScope } from '../../../../shared'
import { useListContext } from '../composables/use-list-context'
import { getRowId } from '../utils'

defineOptions({
  name: 'ListRows',
})

const { listState } = useListContext()

const scope = computed((): RowsScope => {
  const state = listState.value
  const { page, perPage } = state.pagination

  return {
    rows: state.rows.map((row, index) => ({
      ...(row as object),
      _index: (page - 1) * perPage + index + 1,
    })),
    isLoading: state.loader.isLoading,
    setSort: state.setSort,
    sort: state.sort,
  }
})
</script>

// packages/react/src/components/rows.tsx
import { memo, useMemo, type ReactNode } from 'react'
import type { RenderRowArgs, RowsScope } from '../../../../shared'
import { useListContext } from '../context/list-context'
import { getRowId } from '../utils'

type ListRowsProps = {
  children?: (scope: RowsScope) => ReactNode
  row?: (args: RenderRowArgs) => ReactNode
}

function ListRowsInner({ children, row: rowFn }: ListRowsProps) {
  const { listState } = useListContext()
  const { rows = [], loader, error, setSort, sort, pagination, idKey } = listState
  const { initialLoading, isLoading } = loader
  const { page, perPage } = pagination

  const serializedRows = useMemo(
    () =>
      rows.map((row: unknown, index: number) => ({
        ...(row as object),
        _index: (page - 1) * perPage + index + 1,
      })),
    [rows, page, perPage],
  )

  const scope = useMemo(
    (): RowsScope => ({
      rows: serializedRows,
      isLoading,
      setSort,
      sort,
    }),
    [serializedRows, isLoading, setSort, sort],
  )

  if (initialLoading) return null

  if (!rows || rows.length === 0) {
    return null
  }

  if (error) return null

  return (
    <div className="react-list__rows">
      {children && typeof children === 'function'
        ? children(scope)
        : rowFn
          ? serializedRows.map((row, index) => (
              <div key={getRowId(row, idKey) ?? index}>{rowFn({ row, index })}</div>
            ))
          : children
            ? children
            : serializedRows.map((row, index) => (
                <div key={getRowId(row, idKey) ?? index}>
                  <pre>{JSON.stringify(row, null, 2)}</pre>
                </div>
              ))}
    </div>
  )
}

export const ListRows = memo(ListRowsInner) as typeof ListRowsInner
