// packages/vue/src/components/search.vue
<template>
  <div class="vue-list__search">
    <slot v-bind="scope">
      <input
        type="text"
        :value="localSearch"
        @input="handleInput(($event.target as HTMLInputElement).value)"
        placeholder="Search..."
      />
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import type { SearchComponentOptions, SearchScope } from '../../../../shared'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListSearch',
})

const props = withDefaults(defineProps<SearchComponentOptions>(), {
  debounceTime: 500,
})

const { listState } = useListContext()
const localSearch = ref(listState.value.search)

watch(
  () => listState.value.search,
  (value) => {
    if (value !== localSearch.value) {
      localSearch.value = value
    }
  },
)

let debounceTimer: ReturnType<typeof setTimeout> | null = null

function handleInput(value: string) {
  localSearch.value = value

  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }

  debounceTimer = setTimeout(() => {
    listState.value.setSearch(value)
  }, props.debounceTime)
}

onUnmounted(() => {
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
})

const scope = computed(
  (): SearchScope => ({
    search: localSearch.value,
    setSearch: handleInput,
  }),
)
</script>

// packages/react/src/components/search.tsx
import { memo, useEffect, useRef, useState, type ReactNode } from 'react'
import type { SearchComponentOptions, SearchScope } from '../../../../shared'
import { useListContext } from '../context/list-context'

type ListSearchProps = SearchComponentOptions & {
  children?: (scope: SearchScope) => ReactNode
}

export const ListSearch = memo(({ children, debounceTime = 500 }: ListSearchProps) => {
  const { listState } = useListContext()
  const { search, setSearch } = listState
  const [localSearch, setLocalSearch] = useState(search ?? '')
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    if (search !== localSearch) {
      setLocalSearch(search ?? '')
    }
  }, [search])

  const handleChange = (value: string) => {
    setLocalSearch(value)

    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current)
    }

    debounceTimerRef.current = setTimeout(() => {
      setSearch(value)
    }, debounceTime)
  }

  useEffect(() => {
    return () => {
      if (debounceTimerRef.current) {
        clearTimeout(debounceTimerRef.current)
      }
    }
  }, [])

  const scope: SearchScope = {
    search: localSearch,
    setSearch: handleChange,
  }

  return (
    <div className="react-list__search">
      {children ? (
        children(scope)
      ) : (
        <input
          type="text"
          value={localSearch}
          onChange={(e) => handleChange(e.target.value)}
          placeholder="Search..."
        />
      )}
    </div>
  )
})
