// apps/react/story/src/stories/react-list/react-list-demo.tsx
import { useMemo, useState } from 'react'
import ReactList, {
  ListEmpty,
  ListError,
  ListInitialLoader,
  ListItems,
  ListLoadMore,
  ListLoader,
  ListPagination,
  ListPerPage,
  ListRefresh,
  ListSearch,
  ListSummary,
} from '@shilp.dev/react-list'
import type { ListSort } from '@shilp.dev/list-types'
import {
  createRequestHandler,
  type CreateRequestHandlerOptions,
} from '@/api/request-handler'
import { formatSkillDate, type Skill } from '@/types/skill'
import './react-list-demo.css'

const PER_PAGE_OPTIONS = [8, 10, 15, 25, 50, 100]

export interface ReactListDemoProps {
  endpoint?: string
  page?: number
  perPage?: number
  paginationMode?: 'pagination' | 'loadMore'
  /**
   * Serializable options for the demo request handler.
   * Sample JSON: `{ "forceEmpty": false, "shouldFail": false }`
   */
  requestHandler?: CreateRequestHandlerOptions
  count?: number
}

function toggleSort(
  sort: ListSort,
  setSort: (next: { by: string; order: 'asc' | 'desc' }) => void,
  by: string,
) {
  const currentOrder = sort.sortBy === by ? sort.sortOrder : ''
  const order: 'asc' | 'desc' = currentOrder === 'asc' ? 'desc' : 'asc'
  setSort({ by, order })
}

export function ReactListDemo(props: ReactListDemoProps) {
  const listKey = [
    props.endpoint,
    props.page,
    props.perPage,
    props.paginationMode,
    props.count,
    props.requestHandler?.forceEmpty,
    props.requestHandler?.shouldFail,
  ].join(':')

  return <ReactListDemoInner key={listKey} {...props} />
}

function ReactListDemoInner({
  endpoint = 'skills',
  page = 1,
  perPage = 10,
  paginationMode = 'pagination',
  requestHandler,
  count,
}: ReactListDemoProps) {
  const [filters, setFilters] = useState<Record<string, string | undefined>>({})
  const handler = useMemo(
    () => createRequestHandler(requestHandler ?? {}),
    [requestHandler],
  )
  const perPageOptions = useMemo(() => {
    if (PER_PAGE_OPTIONS.includes(perPage)) {
      return PER_PAGE_OPTIONS
    }

    return [...PER_PAGE_OPTIONS, perPage].sort((a, b) => a - b)
  }, [perPage])

  function onStatusChange(value: string) {
    setFilters((current) => ({
      ...current,
      status: value === 'all' ? undefined : value,
    }))
  }

  return (
    <div className="react-list-demo">
      <ReactList
        endpoint={endpoint}
        page={page}
        perPage={perPage}
        paginationMode={paginationMode}
        requestHandler={handler}
        count={count}
        filters={filters}
      >
        <div className="react-list-demo__toolbar">
          <ListSearch>
            {({ search, setSearch }) => (
              <input
                type="search"
                className="react-list-demo__input"
                value={search}
                placeholder="Search skills..."
                onChange={(event) => setSearch(event.target.value)}
              />
            )}
          </ListSearch>

          <label className="react-list-demo__filter">
            Status
            <select
              className="react-list-demo__select"
              onChange={(event) => onStatusChange(event.target.value)}
            >
              <option value="all">All</option>
              <option value="draft">Draft</option>
              <option value="published">Published</option>
              <option value="archived">Archived</option>
            </select>
          </label>
        </div>

        <ListInitialLoader>
          <p className="react-list-demo__message">Loading initial data...</p>
        </ListInitialLoader>

        <ListEmpty>
          <p className="react-list-demo__message">No skills found.</p>
        </ListEmpty>

        <ListError>
          {({ error }) => (
            <div className="react-list-demo__error">
              <p>{error.message}</p>
              <ListRefresh>
                {({ refresh, isLoading }) => (
                  <button
                    type="button"
                    className="react-list-demo__button"
                    disabled={isLoading}
                    onClick={refresh}
                  >
                    Try again
                  </button>
                )}
              </ListRefresh>
            </div>
          )}
        </ListError>

        <ListItems>
          {({ items, sort, setSort }) => (
            <div className="react-list-demo__table-wrap">
              <ListLoader>
                <p className="react-list-demo__overlay">Updating...</p>
              </ListLoader>

              <table className="react-list-demo__table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>
                      <button
                        type="button"
                        className="react-list-demo__sort"
                        onClick={() => toggleSort(sort, setSort, 'name')}
                      >
                        Name
                      </button>
                    </th>
                    <th>Status</th>
                    <th>
                      <button
                        type="button"
                        className="react-list-demo__sort"
                        onClick={() => toggleSort(sort, setSort, 'date_updated')}
                      >
                        Updated
                      </button>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {(items as unknown as Skill[]).map((item) => (
                    <tr key={item.id}>
                      <td>{item.id}</td>
                      <td>{item.name}</td>
                      <td>{item.status}</td>
                      <td>{formatSkillDate(item.date_updated)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </ListItems>

        <div className="react-list-demo__footer">
          <ListSummary>
            {({ count: total, from, to }) => (
              <span>
                {from} - {to} of {total}
              </span>
            )}
          </ListSummary>

          <ListPerPage options={perPageOptions}>
            {({ perPage: currentPerPage, setPerPage, options }) => (
              <label className="react-list-demo__filter">
                Per page
                <select
                  className="react-list-demo__select"
                  value={String(currentPerPage)}
                  onChange={(event) => setPerPage(Number(event.target.value))}
                >
                  {options.map((option) => (
                    <option key={option.value} value={String(option.value)}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </label>
            )}
          </ListPerPage>

          {paginationMode === 'pagination' ? (
            <ListPagination>
              {({ page: currentPage, pagesToDisplay, hasNext, hasPrev, prev, next, setPage }) => (
                <div className="react-list-demo__pagination">
                  <button
                    type="button"
                    className="react-list-demo__button"
                    disabled={!hasPrev}
                    onClick={prev}
                  >
                    Prev
                  </button>
                  {pagesToDisplay.map((item) => (
                    <button
                      key={item}
                      type="button"
                      className={`react-list-demo__button${
                        item === currentPage ? ' react-list-demo__button--active' : ''
                      }`}
                      onClick={() => setPage(item)}
                    >
                      {item}
                    </button>
                  ))}
                  <button
                    type="button"
                    className="react-list-demo__button"
                    disabled={!hasNext}
                    onClick={next}
                  >
                    Next
                  </button>
                </div>
              )}
            </ListPagination>
          ) : (
            <ListLoadMore>
              {({ loadMore, hasMoreItems, isLoading }) => (
                <button
                  type="button"
                  className="react-list-demo__button"
                  disabled={!hasMoreItems || isLoading}
                  onClick={loadMore}
                >
                  {hasMoreItems ? (isLoading ? 'Loading...' : 'Load more') : 'All loaded'}
                </button>
              )}
            </ListLoadMore>
          )}
        </div>
      </ReactList>
    </div>
  )
}

// apps/vue/story/src/stories/vue-list/vue-list-demo.vue
<template>
  <div class="vue-list-demo">
    <VueList
      :key="listKey"
      :endpoint="endpoint"
      :page="page"
      :per-page="perPage"
      :pagination-mode="paginationMode"
      :request-handler="handler"
      :count="count"
      :sync-page-to-url="false"
      v-model:filters="filters"
    >
      <div class="vue-list-demo__toolbar">
        <ListSearch v-slot="{ search, setSearch }">
          <input
            type="search"
            class="vue-list-demo__input"
            :value="search"
            placeholder="Search skills..."
            @input="setSearch(($event.target as HTMLInputElement).value)"
          />
        </ListSearch>

        <label class="vue-list-demo__filter">
          Status
          <select
            class="vue-list-demo__select"
            @change="onStatusChange(($event.target as HTMLSelectElement).value)"
          >
            <option value="all">All</option>
            <option value="draft">Draft</option>
            <option value="published">Published</option>
            <option value="archived">Archived</option>
          </select>
        </label>
      </div>

      <ListInitialLoader>
        <p class="vue-list-demo__message">Loading initial data...</p>
      </ListInitialLoader>

      <ListEmpty>
        <p class="vue-list-demo__message">No skills found.</p>
      </ListEmpty>

      <ListError v-slot="{ error }">
        <div class="vue-list-demo__error">
          <p>{{ error.message }}</p>
          <ListRefresh v-slot="{ refresh, isLoading }">
            <button type="button" class="vue-list-demo__button" :disabled="isLoading" @click="refresh">
              Try again
            </button>
          </ListRefresh>
        </div>
      </ListError>

      <ListItems v-slot="{ items, sort, setSort }">
        <div class="vue-list-demo__table-wrap">
          <ListLoader>
            <p class="vue-list-demo__overlay">Updating...</p>
          </ListLoader>

          <table class="vue-list-demo__table">
            <thead>
              <tr>
                <th>ID</th>
                <th>
                  <button type="button" class="vue-list-demo__sort" @click="toggleSort(sort, setSort, 'name')">
                    Name
                  </button>
                </th>
                <th>Status</th>
                <th>
                  <button
                    type="button"
                    class="vue-list-demo__sort"
                    @click="toggleSort(sort, setSort, 'date_updated')"
                  >
                    Updated
                  </button>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in items as unknown as Skill[]" :key="item.id">
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.status }}</td>
                <td>{{ formatSkillDate(item.date_updated) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </ListItems>

      <div class="vue-list-demo__footer">
        <ListSummary v-slot="{ count: total, from, to }">
          <span>{{ from }} - {{ to }} of {{ total }}</span>
        </ListSummary>

        <ListPerPage :options="perPageOptions" v-slot="{ perPage: currentPerPage, setPerPage, options }">
          <label class="vue-list-demo__filter">
            Per page
            <select
              class="vue-list-demo__select"
              :value="String(currentPerPage)"
              @change="setPerPage(Number(($event.target as HTMLSelectElement).value))"
            >
              <option v-for="option in options" :key="option.value" :value="String(option.value)">
                {{ option.label }}
              </option>
            </select>
          </label>
        </ListPerPage>

        <ListPagination
          v-if="paginationMode === 'pagination'"
          v-slot="{ page: currentPage, pagesToDisplay, hasNext, hasPrev, prev, next, setPage }"
        >
          <div class="vue-list-demo__pagination">
            <button type="button" class="vue-list-demo__button" :disabled="!hasPrev" @click="prev">
              Prev
            </button>
            <button
              v-for="item in pagesToDisplay"
              :key="item"
              type="button"
              class="vue-list-demo__button"
              :class="{ 'vue-list-demo__button--active': item === currentPage }"
              @click="setPage(item)"
            >
              {{ item }}
            </button>
            <button type="button" class="vue-list-demo__button" :disabled="!hasNext" @click="next">
              Next
            </button>
          </div>
        </ListPagination>

        <ListLoadMore v-else v-slot="{ loadMore, hasMoreItems, isLoading }">
          <button
            type="button"
            class="vue-list-demo__button"
            :disabled="!hasMoreItems || isLoading"
            @click="loadMore"
          >
            {{ hasMoreItems ? (isLoading ? 'Loading...' : 'Load more') : 'All loaded' }}
          </button>
        </ListLoadMore>
      </div>
    </VueList>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { ListSort } from '@shilp.dev/vue-list'
import {
  ListEmpty,
  ListError,
  ListInitialLoader,
  ListItems,
  ListLoadMore,
  ListLoader,
  ListPagination,
  ListPerPage,
  ListRefresh,
  ListSearch,
  ListSummary,
  VueList,
} from '@shilp.dev/vue-list'
import {
  createRequestHandler,
  type CreateRequestHandlerOptions,
} from '@/api/request-handler'
import { formatSkillDate, type Skill } from '@/types/skill'

const PER_PAGE_OPTIONS = [8, 10, 15, 25, 50, 100]

defineOptions({
  name: 'vue-list-demo',
})

const props = withDefaults(
  defineProps<{
    endpoint?: string
    page?: number
    perPage?: number
    paginationMode?: 'pagination' | 'loadMore'
    /**
     * Serializable options for the demo request handler.
     * Sample JSON: `{ "forceEmpty": false, "shouldFail": false }`
     */
    requestHandler?: CreateRequestHandlerOptions
    count?: number
  }>(),
  {
    endpoint: 'skills',
    page: 1,
    perPage: 10,
    paginationMode: 'pagination',
    requestHandler: () => ({ forceEmpty: false, shouldFail: false }),
  },
)

const filters = ref<Record<string, string | undefined>>({})

const listKey = computed(() =>
  [
    props.endpoint,
    props.page,
    props.perPage,
    props.paginationMode,
    props.count,
    props.requestHandler?.forceEmpty,
    props.requestHandler?.shouldFail,
  ].join(':'),
)

const handler = computed(() => createRequestHandler(props.requestHandler ?? {}))

const perPageOptions = computed(() => {
  if (PER_PAGE_OPTIONS.includes(props.perPage)) {
    return PER_PAGE_OPTIONS
  }

  return [...PER_PAGE_OPTIONS, props.perPage].sort((a, b) => a - b)
})

watch(listKey, () => {
  filters.value = {}
})

function onStatusChange(value: string) {
  filters.value = {
    ...filters.value,
    status: value === 'all' ? undefined : value,
  }
}

function toggleSort(
  sort: ListSort,
  setSort: (next: { by: string; order: 'asc' | 'desc' }) => void,
  by: string,
) {
  const currentOrder = sort.sortBy === by ? sort.sortOrder : ''
  const order: 'asc' | 'desc' = currentOrder === 'asc' ? 'desc' : 'asc'
  setSort({ by, order })
}
</script>

<style scoped>
.vue-list-demo {
  font-family: system-ui, sans-serif;
  color: #1e293b;
}

.vue-list-demo__toolbar,
.vue-list-demo__footer {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 12px;
  margin: 16px 0;
}

.vue-list-demo__input,
.vue-list-demo__select {
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  padding: 8px 10px;
  font-size: 14px;
}

.vue-list-demo__filter {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
}

.vue-list-demo__table-wrap {
  position: relative;
  overflow: hidden;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
}

.vue-list-demo__overlay {
  position: absolute;
  inset: 0;
  z-index: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0;
  background: rgb(255 255 255 / 70%);
}

.vue-list-demo__table {
  width: 100%;
  border-collapse: collapse;
}

.vue-list-demo__table th,
.vue-list-demo__table td {
  border-bottom: 1px solid #e2e8f0;
  padding: 10px 12px;
  text-align: left;
}

.vue-list-demo__table th {
  background: #f8fafc;
}

.vue-list-demo__sort {
  border: 0;
  background: transparent;
  color: inherit;
  cursor: pointer;
  font: inherit;
}

.vue-list-demo__pagination {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.vue-list-demo__button {
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  background: #fff;
  padding: 6px 10px;
  cursor: pointer;
}

.vue-list-demo__button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.vue-list-demo__button--active {
  border-color: #2563eb;
  background: #2563eb;
  color: #fff;
}

.vue-list-demo__message,
.vue-list-demo__error {
  padding: 24px;
  text-align: center;
}

.vue-list-demo__error {
  color: #b91c1c;
}
</style>
