// packages/react-list/src/components/attributes.tsx
import { memo, useCallback, useMemo, type ReactNode } from "react";
import type {
  AttributesScope,
  ListAttribute,
  RenderAttributeArgs,
} from "@7span/list-types";
import { useListContext } from "../context/list-context";

type ReactListAttributesProps = {
  children?: ReactNode | ((scope: AttributesScope) => ReactNode);
  renderAttribute?: (args: RenderAttributeArgs) => ReactNode;
};

export const ReactListAttributes = memo(
  ({ children, renderAttribute }: ReactListAttributesProps) => {
    const { listState } = useListContext();
    const { attrs, attrSettings, updateAttr } = listState;

    const normalizedAttrs = attrs as ListAttribute[];

    const handleAttrChange = useCallback(
      (attrName: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
        updateAttr?.(attrName, "visible", e.target.checked);
      },
      [updateAttr]
    );

    const scope = useMemo(
      (): AttributesScope => ({
        attrs: normalizedAttrs,
        attrSettings: attrSettings ?? {},
        updateAttr: updateAttr ?? (() => {}),
      }),
      [normalizedAttrs, attrSettings, updateAttr]
    );

    if (typeof children === "function") {
      return children(scope);
    }

    if (children) {
      return children;
    }

    return (
      <div className="react-list-attributes">
        {normalizedAttrs.map((attr, index) => {
          if (renderAttribute) {
            return renderAttribute({
              key: `attr-${index}`,
              attr,
              updateAttr: updateAttr ?? (() => {}),
              attrSettings: attrSettings ?? {},
            });
          }

          return (
            <label key={`attr-${index}`}>
              <span>{attr.label}</span>
              <input
                type="checkbox"
                checked={attrSettings?.[attr.name]?.visible ?? true}
                onChange={handleAttrChange(attr.name)}
              />
            </label>
          );
        })}
      </div>
    );
  }
);

// packages/vue-list/src/components/attributes.vue
<template>
  <div class="vue-list__attributes">
    <slot name="default" v-bind="scope">
      <template v-for="(attr, index) in scope.attrs" :key="`attr-${index}`">
        <slot :attr="attr" :updateAttr="scope.updateAttr">
          <label>
            <span>{{ attr.label }}</span>
            <input
              type="checkbox"
              :checked="scope.attrSettings?.[attr.name]?.visible"
              @change="
                scope.updateAttr(
                  attr.name,
                  'visible',
                  ($event.target as HTMLInputElement).checked,
                )
              "
            />
          </label>
        </slot>
      </template>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { AttributesScope, ListAttribute } from '@7span/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListAttributes',
})

const { listState } = useListContext()

const scope = computed((): AttributesScope => {
  const state = listState.value

  return {
    attrs: state.attrs as ListAttribute[],
    attrSettings: state.attrSettings ?? {},
    updateAttr: state.updateAttr ?? (() => {}),
  }
})
</script>
