// packages/react/src/components/initial-loader.tsx
import { memo, useMemo, type ReactNode } from "react";
import type { InitialLoaderScope } from "@7span/list-types";
import { useListContext } from "../context/list-context";

type ListInitialLoaderProps = {
  children?: ReactNode | ((scope: InitialLoaderScope) => ReactNode);
};

export const ListInitialLoader = memo(
  ({ children }: ListInitialLoaderProps) => {
    const { listState } = useListContext();
    const { loader } = listState;
    const { initialLoading } = loader;

    const scope = useMemo(
      (): InitialLoaderScope => ({
        loading: initialLoading,
      }),
      [initialLoading]
    );

    if (!initialLoading) {
      return null;
    }

    return (
      <div className="react-list-initial-loader">
        {typeof children === "function"
          ? children(scope)
          : children || <p>Initial Loading...</p>}
      </div>
    );
  }
);

// packages/vue-list/src/components/initial-loader.vue
<template>
  <div v-if="scope.loading" class="vue-list__initial-loader">
    <slot v-bind="scope">
      <p>Initial Loading...</p>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { InitialLoaderScope } from '@7span/list-types'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListInitialLoader',
})

const { listState } = useListContext()

const scope = computed((): InitialLoaderScope => ({
  loading: listState.value.loader.initialLoading,
}))
</script>
