// packages/react/src/components/columns.tsx
import { memo, useCallback, useMemo, type ReactNode } from 'react'
import type { ColumnsScope, ListColumn, RenderColumnArgs } from '../../../../shared'
import { useListContext } from '../context/list-context'

type ListColumnsProps = {
  children?: ReactNode | ((scope: ColumnsScope) => ReactNode)
  column?: (args: RenderColumnArgs) => ReactNode
}

export const ListColumns = memo(({ children, column: columnFn }: ListColumnsProps) => {
  const { listState } = useListContext()
  const { columns, columnSettings, updateColumn } = listState

  const normalizedColumns = columns as ListColumn[]

  const handleColumnChange = useCallback(
    (columnName: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
      updateColumn?.(columnName, 'visible', e.target.checked)
    },
    [updateColumn],
  )

  const scope = useMemo(
    (): ColumnsScope => ({
      columns: normalizedColumns,
      columnSettings: columnSettings ?? {},
      updateColumn: updateColumn ?? (() => {}),
    }),
    [normalizedColumns, columnSettings, updateColumn],
  )

  return (
    <div className="react-list__columns">
      {typeof children === 'function'
        ? children(scope)
        : children
          ? children
          : normalizedColumns.map((column, index) => {
              if (columnFn) {
                return columnFn({
                  key: `column-${index}`,
                  column,
                  updateColumn: updateColumn ?? (() => {}),
                  columnSettings: columnSettings ?? {},
                })
              }

              return (
                <label key={`column-${index}`}>
                  <span>{column.label}</span>
                  <input
                    type="checkbox"
                    checked={columnSettings?.[column.name]?.visible ?? true}
                    onChange={handleColumnChange(column.name)}
                  />
                </label>
              )
            })}
    </div>
  )
})

// packages/vue/src/components/columns.vue
<template>
  <div class="vue-list__columns">
    <slot v-bind="scope">
      <template v-for="(column, index) in scope.columns" :key="`column-${index}`">
        <slot
          name="column"
          :column="column"
          :updateColumn="scope.updateColumn"
          :columnSettings="scope.columnSettings"
        >
          <label>
            <span>{{ column.label }}</span>
            <input
              type="checkbox"
              :checked="scope.columnSettings?.[column.name]?.visible ?? true"
              @change="
                scope.updateColumn(
                  column.name,
                  'visible',
                  ($event.target as HTMLInputElement).checked,
                )
              "
            />
          </label>
        </slot>
      </template>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ColumnsScope, ListColumn } from '../../../../shared'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListColumns',
})

const { listState } = useListContext()

const scope = computed((): ColumnsScope => {
  const state = listState.value

  return {
    columns: state.columns as ListColumn[],
    columnSettings: state.columnSettings ?? {},
    updateColumn: state.updateColumn ?? (() => {}),
  }
})
</script>
