// packages/react-list/src/components/error.tsx
import { memo, type ReactNode } from "react";
import type { ErrorScope } from "@7span/list-types";
import { useListContext } from "../context/list-context";

type ListErrorProps = {
  children?: ReactNode | ((scope: ErrorScope) => ReactNode);
};

export const ListError = memo(({ children }: ListErrorProps) => {
  const { listState } = useListContext();
  const { error, loader } = listState;
  const { isLoading } = loader;

  if (!error || isLoading) {
    return null;
  }

  return (
    <div className="react-list-error">
      {typeof children === "function"
        ? children({ error })
        : children || (
            <div>
              <h3>Error occurred</h3>
              <pre>
                {error.name}: {error.message}
              </pre>
            </div>
          )}
    </div>
  );
});

// packages/vue/src/components/error.vue
<template>
  <div v-if="listState.error && !listState.loader.isLoading" class="vue-list__error">
    <slot :error="listState.error">
      <div>
        <h3>Error occurred</h3>
        <pre>{{ listState.error.name }}: {{ listState.error.message }}</pre>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListError',
})

const { listState } = useListContext()
</script>
