// packages/react/src/components/refresh.tsx
import { type ReactNode } from 'react'
import type { RefreshScope } from '../../../../shared'
import { useListContext } from '../context/list-context'

type ListRefreshProps = {
  children?: (scope: RefreshScope) => ReactNode
}

export const ListRefresh = ({ children }: ListRefreshProps) => {
  const { listState } = useListContext()
  const { loader, refresh } = listState
  const { isLoading, initialLoading } = loader

  const handleRefresh = () => {
    refresh({ isRefresh: true })
  }

  const scope: RefreshScope = {
    isLoading,
    refresh: handleRefresh,
  }

  if (initialLoading) return null

  return (
    <div className="react-list__refresh">
      {typeof children === 'function'
        ? children(scope)
        : children || (
            <button onClick={handleRefresh} disabled={isLoading}>
              {isLoading ? 'Loading...' : 'Refresh'}
            </button>
          )}
    </div>
  )
}

// packages/vue/src/components/refresh.vue
<template>
  <div v-if="!listState.loader.initialLoading" class="vue-list__refresh">
    <slot v-bind="scope">
      <button type="button" :disabled="scope.isLoading" @click="scope.refresh">
        {{ scope.isLoading ? 'Loading...' : 'Refresh' }}
      </button>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { RefreshScope } from '../../../../shared'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListRefresh',
})

const { listState } = useListContext()

const scope = computed(
  (): RefreshScope => ({
    isLoading: listState.value.loader.isLoading,
    refresh: () => listState.value.refresh({ isRefresh: true }),
  }),
)
</script>
