// packages/react/src/components/summary.tsx
import { type ReactNode } from 'react'
import type { SummaryScope } from '../../../../shared'
import { useListContext } from '../context/list-context'

type ListSummaryProps = {
  children?: (scope: SummaryScope) => ReactNode
}

export const ListSummary = ({ children }: ListSummaryProps) => {
  const { listState } = useListContext()
  const { data, count, pagination, loader, error } = listState
  const { page, perPage } = pagination
  const { initialLoading } = loader

  const summaryData = {
    from: page * perPage - perPage + 1,
    to: Math.min(page * perPage, count),
    visibleCount: data?.length || 0,
  }

  const scope: SummaryScope = {
    ...summaryData,
    count,
  }

  if (initialLoading) return null

  if (!data || data.length === 0) {
    return null
  }

  if (error) {
    return null
  }

  return (
    <div className="react-list__summary">
      {typeof children === 'function' ? (
        children(scope)
      ) : children ? (
        children
      ) : (
        <span>
          Showing <span>{summaryData.visibleCount}</span> items (
          <span>
            {summaryData.from} - {summaryData.to}
          </span>
          ) out of <span>{count}</span>
        </span>
      )}
    </div>
  )
}

// packages/vue/src/components/summary.vue
<template>
  <div v-if="showSummary" class="vue-list__summary">
    <slot v-bind="scope">
      <span>
        Showing <span>{{ scope.visibleCount }}</span> items (
        <span>{{ scope.from }} - {{ scope.to }}</span
        >) out of
        <span>{{ scope.count }}</span>
      </span>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { SummaryScope } from '../../../../shared'
import { useListContext } from '../composables/use-list-context'

defineOptions({
  name: 'ListSummary',
})

const { listState } = useListContext()

const showSummary = computed(() => {
  const state = listState.value
  return !state.loader.initialLoading && state.data.length > 0 && !state.error
})

const scope = computed((): SummaryScope => {
  const state = listState.value
  const { page, perPage } = state.pagination
  const from = page * perPage - perPage + 1
  const to = Math.min(page * perPage, state.count)

  return {
    from,
    to,
    visibleCount: state.data.length,
    count: state.count,
  }
})
</script>
